title: Image Data Team - Turku BioImaging
email: image-data@bioimaging.fi
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username: jekyll

plugins:
  # - jekyll-feed
  - jekyll-postcss
sass:
  sass_dir: _sass
  style: compact

# include:
#   - node_modules/@fortawesom/fontawesome-free/webfonts

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
