# Site
name: "Turku Bioimaging Image Data Team (TBI-IDAT)"
title: "Image Data Team - Turku Bioimaging"
description: "We are a dedicated service for image data management and analysis operating under Turku Bioimaging."
logo: 'assets/images/logo.png'
favicon: 'assets/images/ub.png'
# baseurl: '/'
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  junel:
    name: Junel Solis
    display_name: Junel
    gravatar: d9a9e7f53d61e12ef933d846da67ff7a
    email: junel.solis@abo.fi
    web: https://www.bioimaging.fi
    twitter: https://twitter.com/junelsolis
    description: 
  joanna:
    name: Joanna Pylv채n채inen
    display_name: Joanna    
    # avatar: 'assets/images/avatar.png'
    # gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: joanna.pylvanainen@abo.fi
    web: https://www.bioimaging.fi
    twitter: https://twitter.com/JwPylvanainen
    description: 
  dado:
    name: Dado Tokic
    display_name: Dado
    # avatar: 'assets/images/avatar.png'
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: dado.tokic@abo.fi
    web: https://www.bioimaging.fi
    # twitter: https://twitter.com/junelsolis
    description: 
  pasi:
    name: Pasi Kankaanp채채
    display_name: Pasi
    # avatar: 'assets/images/avatar.png'
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: pkankaan@abo.fi
    web: https://www.bioimaging.fi
    # twitter: https://twitter.com/junelsolis
    description: 

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
